/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assign;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayesh
 */
public class PostgraduateView extends javax.swing.JFrame {
   databases dbsu =new databases();

    /**
     * Creates new form PostgraduateRegister
     */
    public PostgraduateView() {
        initComponents();
        Dimension screensize=Toolkit.getDefaultToolkit().getScreenSize();
        int width=(int) screensize.getWidth();
        int height=(int) screensize.getHeight();
        setSize(width,height-10);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    public PostgraduateView(PostgraduateStudent pg1)  {
        
         initComponents();
        postgraduateNameText.setText(pg1.getName());
        courseCodeText.setText(pg1.getCourseCode()+"");
        postgraduateStudentIdText.setText(pg1.getPostgraduateId());
        postgraduateAddressText.setText(pg1.getAddress());
        qualificationTypeText.setText(pg1.getQualificationType());
       UniversityText.setText(pg1.getUniversity());
       yearOfGraduationText.setText(pg1.getYearOfGraduation()+"");
       userIdText.setText(pg1.getUserId()+"");
       emailText.setText(pg1.getEmail());
       
        undergraduateDegreeText.setText(pg1.getUndergraduateDegree());
         Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
        try {
            cal.setTime(sdf.parse(pg1.getDateOfBirth()));// all done
        } catch (NullPointerException ex) {
            System.out.println(ex);
        } catch (ParseException ex) {
          System.out.println(ex);
       }
        dob.setCalendar(cal);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        userIdText = new javax.swing.JTextField();
        postgraduateNameLabel = new javax.swing.JLabel();
        postgraduateNameText = new javax.swing.JTextField();
        postgraduateDOBLabel = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        postgraduateAddressLabel = new javax.swing.JLabel();
        postgraduateAddressText = new javax.swing.JTextField();
        undergraduateDegreeLabel = new javax.swing.JLabel();
        undergraduateDegreeText = new javax.swing.JTextField();
        qualificationTypeLabel = new javax.swing.JLabel();
        qualificationTypeText = new javax.swing.JTextField();
        universityLabel = new javax.swing.JLabel();
        UniversityText = new javax.swing.JTextField();
        yearOfGraduationLabel = new javax.swing.JLabel();
        yearOfGraduationText = new javax.swing.JTextField();
        postgraduateStudentIdLabel = new javax.swing.JLabel();
        postgraduateStudentIdText = new javax.swing.JTextField();
        courseCodeLabel = new javax.swing.JLabel();
        courseCodeText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Postgraduate Student Register Form");

        userIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userIdLabel.setText("User Id");

        postgraduateNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postgraduateNameLabel.setText("Name");

        postgraduateNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgraduateNameTextActionPerformed(evt);
            }
        });

        postgraduateDOBLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postgraduateDOBLabel.setText("Date of birth");

        postgraduateAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postgraduateAddressLabel.setText("Address");

        undergraduateDegreeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        undergraduateDegreeLabel.setText("Undergraduate degree");

        qualificationTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qualificationTypeLabel.setText("Qualification Type");

        universityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        universityLabel.setText("University");

        yearOfGraduationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearOfGraduationLabel.setText("Year of Graduation");

        postgraduateStudentIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postgraduateStudentIdLabel.setText("Student Id");

        courseCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseCodeLabel.setText("Course Code");

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        Deletebutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deletebutton.setText("Delete");
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm 2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutterstock_236238829.jpg.640x480_q85_crop-center.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearOfGraduationLabel)
                                    .addComponent(universityLabel)
                                    .addComponent(qualificationTypeLabel)
                                    .addComponent(undergraduateDegreeLabel)
                                    .addComponent(postgraduateAddressLabel)
                                    .addComponent(postgraduateDOBLabel)
                                    .addComponent(postgraduateNameLabel)
                                    .addComponent(userIdLabel)
                                    .addComponent(postgraduateStudentIdLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(courseCodeLabel)
                                            .addComponent(updateButton)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(courseCodeText)
                                    .addComponent(yearOfGraduationText)
                                    .addComponent(UniversityText)
                                    .addComponent(qualificationTypeText)
                                    .addComponent(undergraduateDegreeText)
                                    .addComponent(postgraduateAddressText)
                                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(postgraduateNameText)
                                    .addComponent(userIdText)
                                    .addComponent(postgraduateStudentIdText)
                                    .addComponent(emailText)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Deletebutton)
                                .addGap(108, 108, 108)
                                .addComponent(homeButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userIdLabel)
                                    .addComponent(userIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(postgraduateStudentIdLabel)
                                    .addComponent(postgraduateStudentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(postgraduateNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addComponent(postgraduateNameLabel))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postgraduateDOBLabel))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postgraduateAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postgraduateAddressLabel))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(undergraduateDegreeText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(undergraduateDegreeLabel))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qualificationTypeLabel)
                            .addComponent(qualificationTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(universityLabel)
                            .addComponent(UniversityText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearOfGraduationLabel)
                            .addComponent(yearOfGraduationText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseCodeLabel)
                            .addComponent(courseCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(Deletebutton)
                    .addComponent(homeButton))
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postgraduateNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgraduateNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postgraduateNameTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       PostgraduateStudent up1=new PostgraduateStudent();
         up1.setUserId(Integer.parseInt(userIdText.getText()));
        up1.setName(postgraduateNameText.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dob1 = sdf.format(dob.getDate());
        up1.setDateOfBirth(dob1);
        up1.setAddress(postgraduateAddressText.getText());
        up1.setPostgraduateId(postgraduateStudentIdText.getText());
     
        up1.setQualificationType(qualificationTypeText.getText());
        up1.setUniversity(UniversityText.getText());
        up1.setYearOfGraduation(Integer.parseInt(yearOfGraduationText.getText()));
        up1.setPostgraduateId(postgraduateStudentIdText.getText());
        up1.setCourseCode(Integer.parseInt(courseCodeText.getText()));
        up1.setEmail(emailText.getText());

     
        
        boolean result2=dbsu.updatePostgraduateStudent(up1);
             if(result2==true){
            JOptionPane.showMessageDialog(this, "Successfully Updated");
            //undergraduateClear();
            this.dispose();   //Jframe will dissapear after we click ok on the message
        }else{
            JOptionPane.showMessageDialog(this, "Sorry an error  occured while Updating");
        }

    

    }                                            

    private void updateRankTextActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
       PostgraduateStudent up1=new PostgraduateStudent();
       up1.setUserId(Integer.parseInt(userIdText.getText()));
      
        boolean result2=dbsu.deletePostgraduateStudent(up1);
             if(result2==true){
            JOptionPane.showMessageDialog(this, "Successfully Deleted");
            //undergraduateClear();
            this.dispose();   //Jframe will dissapear after we click ok on the message
        }else{
            JOptionPane.showMessageDialog(this, "Sorry an error  occured while Deleting");
        }

    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
      MainFrame mf1=new MainFrame();
       mf1.setVisible(true);
       mf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebutton;
    private javax.swing.JTextField UniversityText;
    private javax.swing.JLabel courseCodeLabel;
    private javax.swing.JTextField courseCodeText;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel postgraduateAddressLabel;
    private javax.swing.JTextField postgraduateAddressText;
    private javax.swing.JLabel postgraduateDOBLabel;
    private javax.swing.JLabel postgraduateNameLabel;
    private javax.swing.JTextField postgraduateNameText;
    private javax.swing.JLabel postgraduateStudentIdLabel;
    private javax.swing.JTextField postgraduateStudentIdText;
    private javax.swing.JLabel qualificationTypeLabel;
    private javax.swing.JTextField qualificationTypeText;
    private javax.swing.JLabel undergraduateDegreeLabel;
    private javax.swing.JTextField undergraduateDegreeText;
    private javax.swing.JLabel universityLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdText;
    private javax.swing.JLabel yearOfGraduationLabel;
    private javax.swing.JTextField yearOfGraduationText;
    // End of variables declaration//GEN-END:variables
}
